%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                                                                          %
%        Generated by MATLAB 8.1, MATLAB Coder 2.4 and HDL Coder 3.2      %
%                                                                          %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%#codegen
function [x_out,y_out,r_out,g_out,b_out] = hdllpf13_FixPt(x_in,y_in,r_in,g_in,b_in)

fm = fimath('RoundingMethod', 'Floor', 'OverflowAction', 'Wrap', 'ProductMode', 'FullPrecision', 'MaxProductWordLength', 128, 'SumMode', 'FullPrecision', 'MaxSumWordLength', 128);
persistent OrigImg
persistent x1 x2 y1 y2
if isempty( OrigImg )
    OrigImg = fi(zeros( 3, 1 ), 0, 1, 0, fm);
    x1 = fi(0, 0, 10, 0, fm);
    x2 = fi(0, 0, 10, 0, fm);
    y1 = fi(0, 0, 9, 0, fm);
    y2 = fi(0, 0, 9, 0, fm);
end
D = fi([ 1*fi(1/9, 0, 14, 17), 1*fi(1/9, 0, 14, 17), 1*fi(1/9, 0, 14, 17); 1*fi(1/9, 0, 14, 17), 1*fi(1/9, 0, 14, 17), 1*fi(1/9, 0, 14, 17); 1*fi(1/9, 0, 14, 17), 1*fi(1/9, 0, 14, 17), 1*fi(1/9, 0, 14, 17) ], 0, 14, 17, fm);
RGB = fi([ r_in; g_in; b_in ], 0, 9, 0, fm);
OrigImg_1 = fi(D*RGB, 0, 14, 7, fm);
r_out = fi(OrigImg_1( 1 ), 0, 14, 7, fm);
g_out = fi(OrigImg_1( 2 ), 0, 14, 7, fm);
b_out = fi(OrigImg_1( 3 ), 0, 14, 7, fm);
x_out = fi(x2, 0, 10, 0, fm);
x2 = fi(x1, 0, 10, 0, fm);
x1 = fi(x_in, 0, 10, 0, fm);
y_out = fi(y2, 0, 9, 0, fm);
y2 = fi(y1, 0, 9, 0, fm);
y1 = fi(y_in, 0, 9, 0, fm);
end
